# docker-compose.yml
version: '3.3'
services:
  api:
      build: ./app
      ports:
        - 5000:5000
      volumes: 
        - ./app:/app
      links:
        - db
      depends_on: 
        - db
      environment:
        - MONGO_DB_HOST=db
  db:
      image: mongo
