# docker-compose.yml
version: '3.7'
services:
  api:
      build: ./app
      ports:
        - 5000:5000
      volumes: 
        - ./app:/app
      links:
        - db
      depends_on: 
        - db
  db:
      image: mongo
